### ISSUE TITLE
Cannot connect to node server

### ISSUE THREAD

**Issue by sandinmyjoints** [NicolasPetton/Indium#205] opened 2019-04-13 18:27 UTC
I am running a node (v8.14.0) server in docker. In the Docker container, it starts with `node --inspect=0.0.0.0:9229 server-single.js`.

On my (macOS) host, I can talk to it:

```
$ curl 127.0.0.1:9229/json/list
[ {
  "description": "node.js instance",
  "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=172.24.0.5:9229/187b6aea-3d66-47ae-a2ef-795ee7859eed",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "187b6aea-3d66-47ae-a2ef-795ee7859eed",
  "title": "server-single.js",
  "type": "node",
  "url": "file:///usr/src/app/server-single.js",
  "webSocketDebuggerUrl": "ws://172.24.0.5:9229/187b6aea-3d66-47ae-a2ef-795ee7859eed"
} ]
```

When I browse to chrome://inspect, it appears as a target and I can connect to it.

My .indium.json is this:

```json
{
  "configurations": [
    {
      "name": "Neodarwin node",
      "type": "node",
      "host": "127.0.0.1",
      "port": 9229
    }
  ]
}
```

When I run `indium-connect`, this is what I see the indium debug log (there is a gap of 10 or more seconds between the send and the receives):

```
Sent: ((id . 71) (type . connection) (payload (action . connect) (directory .
/Users/william/scm/sd/neodarwin/) (name . Neodarwin node)))

Received: ((id . 71) (type . error) (payload (error . socket hang up)))

Received: ((id . 71) (type . success) (payload . Connected to Node!))
```

The repl window opens, but I cannot evaluate any forms, I just get the message "Indium server error: not connected".

Any ideas?

**Comment by sandinmyjoints** [comment] 2019-04-13 18:32
Similar to https://github.com/NicolasPetton/Indium/issues/194, if I run `node inspect localhost:9229` (which connects and drops me into the debugger), and then I run `indium-connect`, the debug output changes to this:

```
Sent: ((id . 79) (type . connection) (payload (action . connect) (directory . /Users/william/scm/sd/neodarwin/) (name . Neodarwin node)))

Received: ((id . 79) (type . error) (payload (error . No inspectable targets)))

Received: ((id . 79) (type . success) (payload . Connected to Node!))
```

**Comment by sandinmyjoints** [comment] 2019-04-13 18:52
I notice that the debug server returns `"webSocketDebuggerUrl": "ws://172.24.0.5:9229/187b6aea-3d66-47ae-a2ef-795ee7859eed"` -- I'm guessing the 172.24.0.5 maybe lives inside the docker container, and if indium is getting this value and trying to connect to it from host, it will not be able to reach it? Or something like that. (But then why is Chrome able to connect to it?)

**Comment by sandinmyjoints** [comment] 2019-04-13 19:00
`indium-nodejs--process-filter-function`'s docstring says

>   "Return a process filter function for CONF.
> The function detects the socket URL to connect to from the process output."

I'm not great at emacs lisp, but I'm missing how it detects the socket url:

```emacs-lisp

(defun indium-nodejs--process-filter-function (conf)
  "Return a process filter function for CONF.
The function detects the socket URL to connect to from the
process output."
  (let ((connected))
    (lambda (process output)
      ;; Append output to the process buffer
      ;; WJB
      (message (format "output is %s" output))
      (with-current-buffer (process-buffer process)
        (goto-char (point-max))
        (insert output))
      (when (and (not connected)
                 (string-match-p "Debugger listening on" output))
        ;; Node will keep outputing the "Debugger listening on" message after
        ;; each deconnection, so only try to connect one.
        (setq connected t)
        (let-alist conf
          (indium-client-connect (file-name-directory .projectFile) .name))))))
```

**Comment by NicolasPetton** [comment] 2019-06-12 21:07
Hi! Sorry for the late answer, I'm trying to reproduce the issue right now.

**Comment by NicolasPetton** [comment] 2019-06-12 21:19
For the socket URL, look at the server component (nodejs side) of Indium, the Emacs client (the Elisp side) only communicates with it.
https://github.com/NicolasPetton/Indium/tree/master/server

**Comment by NicolasPetton** [comment] 2019-06-12 21:27
@sandinmyjoints I'm trying to reproduce the issue, but I think I'm doing something wrong.

I created a repository at https://github.com/NicolasPetton/indium-docker-issue

When I try to connect to the exposed port `9229` from docker, I get a connection reset, whether I try to connect from Indium or from `curl`.

It looks like I need your help first to be able to debug the issue :)

**Comment by NicolasPetton** [comment] 2019-06-13 19:28
@sandinmyjoints I found why it didn't work in my repository, the last commit fixed it.

Everything works fine with the latest version of Indium, can you have a look at my setup in https://github.com/NicolasPetton/indium-docker-issue?

**Comment by sandinmyjoints** [comment] 2019-06-15 21:25
Thanks for responding, @NicolasPetton! I will try this out the next opportunity I have -- really looking forward to using indium!

**Comment by NicolasPetton** [comment] 2019-06-26 19:50
@sandinmyjoints I'm closing this issue for now as from my experiment the latest version of Indium works fine with Docker. If it's still an issue for you, feel free to reopen it.

**Closed by NicolasPetton** 2019-06-26 19:50 UTC
Labels: bug, nodejs
